name: Publish NuGet Package

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version (leave empty to use tag or default)'
        required: false

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    - name: Install NuGet CLI
      run: dotnet tool install --global NuGet.CommandLine
      
    - name: Set version
      id: set-version
      run: |
        if [ "${{ github.event.inputs.version }}" != "" ]; then
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
        elif [[ $GITHUB_REF == refs/tags/v* ]]; then
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        else
          echo "VERSION=1.0.0-$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV
        fi
        echo "Using version: ${{ env.VERSION }}"
    
    - name: Update .nuspec version
      run: |
        sed -i "s/<version>.*<\/version>/<version>${{ env.VERSION }}<\/version>/" VRising.UnhollowedX.Client.nuspec
    
    - name: Create NuGet package
      run: nuget pack VRising.UnhollowedX.Client.nuspec
    
    - name: Push to NuGet.org
      run: dotnet nuget push "VRising.UnhollowedX.Client.${{ env.VERSION }}.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
    
    - name: Upload NuGet package as artifact
      uses: actions/upload-artifact@v4
      with:
        name: nuget-package
        path: "*.nupkg"